# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('PATIENT', 'Patients or drug buyers'), ('PHARMACISTS', 'Drug store owner'), ('ADMIN', 'An adminstrator superuser')], default='PATIENT', max_length=50),
        ),
    ]
