# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_auth', '0003_auto_20160118_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
