# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharm_name', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=60)),
                ('county', models.CharField(max_length=60)),
            ],
        ),
    ]
