# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together=set([('pharmacy', 'drug')]),
        ),
    ]
