# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_auto_20160308_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
