# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_pharmacy_pharm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='county',
            field=models.CharField(default='NAIROBI', max_length=60),
        ),
    ]
