# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_drugs_recommended_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drugs',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prices',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
