# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_auto_20160121_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='pharm_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='pharm_code',
            new_name='no',
        ),
    ]
