# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_auto_20160125_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='county',
            field=models.CharField(default='NAIROBI', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='town',
            field=models.CharField(max_length=100),
        ),
    ]
