# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_pharmacy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prices', to='pharmacies.Pharmacy'),
        ),
    ]
