# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxcui', models.CharField(default='', max_length=20)),
                ('generic_rxcui', models.CharField(blank=True, max_length=20)),
                ('tty', models.CharField(default='', max_length=20)),
                ('full_name', models.CharField(default='', max_length=3000)),
                ('rxn_dose_form', models.CharField(default='', max_length=100)),
                ('full_generic_name', models.CharField(default='', max_length=3000)),
                ('brand_name', models.CharField(blank=True, max_length=500)),
                ('display_name', models.CharField(default='', max_length=3000)),
                ('route', models.CharField(default='', max_length=100)),
                ('new_dose_form', models.CharField(default='', max_length=100)),
                ('strength', models.CharField(default='', max_length=500)),
                ('suppress_for', models.CharField(blank=True, max_length=30)),
                ('display_name_synonym', models.CharField(blank=True, max_length=500)),
                ('is_retired', models.CharField(blank=True, max_length=20)),
                ('sxdg_rxcui', models.CharField(blank=True, max_length=20)),
                ('sxdg_tty', models.CharField(blank=True, max_length=20)),
                ('sxdg_name', models.CharField(blank=True, max_length=3000)),
                ('psn', models.CharField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Drugs')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.Pharmacy')),
            ],
        ),
    ]
