# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='form',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
