# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20160121_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugs',
            old_name='form',
            new_name='sxdg_tty',
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='code',
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='drugs',
            name='brand_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drugs',
            name='display_name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='drugs',
            name='display_name_synonym',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drugs',
            name='full_generic_name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='drugs',
            name='full_name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='drugs',
            name='generic_rxcui',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drugs',
            name='is_retired',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drugs',
            name='new_dose_form',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drugs',
            name='psn',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='drugs',
            name='route',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drugs',
            name='rxcui',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='drugs',
            name='rxn_dose_form',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drugs',
            name='strength',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='drugs',
            name='suppress_for',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='drugs',
            name='sxdg_name',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='drugs',
            name='sxdg_rxcui',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='drugs',
            name='tty',
            field=models.CharField(default='', max_length=20),
        ),
    ]
