# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20160124_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='generic_rxcui',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='is_retired',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='rxcui',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='sxdg_rxcui',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
